### ISSUE TITLE
Question about the `ParseMode` types of `Inbound` `DataChannel`

### ISSUE THREAD

**Issue by hisaac** [tannerdsilva/SwiftSlash#17]
I noticed that in your example code, you used the `.lf` type for stdout, and `.unparsedRaw` for stderr:

https://github.com/tannerdsilva/SwiftSlash/blob/dbcd79125918644c348471853ef5332d650548db/README.md?plain=1#L75

I'm not familiar enough to know the reason to use one or the other. Was this decision intentional? Should a person normally use these types for the different `DataChannel`s?

**Comment by tannerdsilva** [comment]
Hey Isaac, thanks for the contributions to the library. I look forward to delivering version 4 closely with Swift 6. This current 3.x version has served me well for multiple years, but is beginning to grow in need of some changes long term.

My desire for SwiftSlash's public API was to make it as generally flexible as possible. Shell scripting in itself is a very open ended thing, and I have no idea what kinds of workflows SwiftSlash may or may not be used for.

From my view: I hit a particular issue with early implementations I wrote that were simply parsing for `.lf` byte (non-configurable). I found a particular branch of PHP scripts in my production env were using `.crlf` linebreaks, which is what lead to the API we see in the current releases.

To answer your question:

The particular way I showed it in the docs was a bit silly, but I just wanted to show that you can independently assign the parse mode for any data channel.

For any single shell command, I think its reasonable to assume that between `STDOUT`, and `STDERR`, the line break mode (or lack thereof) would be consistent across both. But of course, SwiftSlash can facilitate the wildly unlikely need where they need to be individually configured.

Most shell commands output lines of data, so it is convenient that SwiftSlash parses these lines on its own, and doesn't force you to find these byes yourself. SwiftSlash only runs on UNIX which is why I chose `.lf` as default over `.crlf`.

Examples where perhaps `.unparsedRaw` might be desired: a shell command whose `STDOUT` is writing binary data instead of human-readable lines. Maybe something like `qrencode` which might write the contents of the binary content of its output directly to `STDOUT`. In this scenario, it is ideal if SwiftSlash does NOT parse or extract any bytes in the bytestream, because the user (developer) would simply have to add these bytes into the data again. So in this particular mode `.unparsaedRaw`, SwiftSlash simply passes the data into the AsyncStream as soon as it is provided from the system kernel, and does not wait for a "trigger byte" to separate the individual elements in the AsyncStream.

I hope that answers your question completely. If you have any feedback or suggestions I'd love to hear them!

**Comment by hisaac** [comment]
Brilliant, thank you for the detailed answer! That all makes sense to me. 🙏
